name: confluent-kafka-python
lang: python
lang_version: '3.8'
git:
  enable: true
sonarqube:
  enable: true
  analysis_exclusions:
    - '**/*.pb.*'
    - '**/mk-include/**/*'
    - examples/**
semaphore:
  enable: true
  pipeline_enable: false
