"""
Configuration constants for Kafka clients.
​
Modeled after java client: https://kafka.apache.org/20/javadoc/constant-values.html
"""
​
​
class AdminClientConfig:
    """
    The AdminClient configuration class, which also contains constants for configuration entry names.
    """
    BOOTSTRAP_SERVERS_CONFIG = "bootstrap.servers"
    CLIENT_ID_CONFIG = "client.id"
    CONNECTIONS_MAX_IDLE_MS_CONFIG = "connections.max.idle.ms"
    DEFAULT_SECURITY_PROTOCOL = "PLAINTEXT"
    METADATA_MAX_AGE_CONFIG = "metadata.max.age.ms"
    METRIC_REPORTER_CLASSES_CONFIG = "metric.reporters"
    METRICS_NUM_SAMPLES_CONFIG = "metrics.num.samples"
    METRICS_RECORDING_LEVEL_CONFIG = "metrics.recording.level"
    METRICS_SAMPLE_WINDOW_MS_CONFIG = "metrics.sample.window.ms"
    RECEIVE_BUFFER_CONFIG = "receive.buffer.bytes"
    RECONNECT_BACKOFF_MAX_MS_CONFIG = "reconnect.backoff.max.ms"
    RECONNECT_BACKOFF_MS_CONFIG = "reconnect.backoff.ms"
    REQUEST_TIMEOUT_MS_CONFIG = "request.timeout.ms"
    RETRIES_CONFIG = "retries"
    RETRY_BACKOFF_MS_CONFIG = "retry.backoff.ms"
    SECURITY_PROTOCOL_CONFIG = "security.protocol"
    SEND_BUFFER_CONFIG = "send.buffer.bytes"
​
​
class ConsumerConfig:
    """
    The consumer configuration keys
    """
    AUTO_COMMIT_INTERVAL_MS_CONFIG = "auto.commit.interval.ms"
    AUTO_OFFSET_RESET_CONFIG = "auto.offset.reset"
    BOOTSTRAP_SERVERS_CONFIG = "bootstrap.servers"
    CHECK_CRCS_CONFIG = "check.crcs"
    CLIENT_ID_CONFIG = "client.id"
    CONNECTIONS_MAX_IDLE_MS_CONFIG = "connections.max.idle.ms"
    DEFAULT_API_TIMEOUT_MS_CONFIG = "default.api.timeout.ms"
    DEFAULT_EXCLUDE_INTERNAL_TOPICS = True
    DEFAULT_FETCH_MAX_BYTES = 52428800
    DEFAULT_MAX_PARTITION_FETCH_BYTES = 1048576
    ENABLE_AUTO_COMMIT_CONFIG = "enable.auto.commit"
    EXCLUDE_INTERNAL_TOPICS_CONFIG = "exclude.internal.topics"
    FETCH_MAX_BYTES_CONFIG = "fetch.max.bytes"
    FETCH_MAX_WAIT_MS_CONFIG = "fetch.max.wait.ms"
    FETCH_MIN_BYTES_CONFIG = "fetch.min.bytes"
    GROUP_ID_CONFIG	= "group.id"
    HEARTBEAT_INTERVAL_MS_CONFIG = "heartbeat.interval.ms"
    INTERCEPTOR_CLASSES_CONFIG = "interceptor.classes"
    ISOLATION_LEVEL_CONFIG = "isolation.level"
    KEY_DESERIALIZER_CLASS_CONFIG = "key.deserializer"
    MAX_PARTITION_FETCH_BYTES_CONFIG = "max.partition.fetch.bytes"
    MAX_POLL_INTERVAL_MS_CONFIG = "max.poll.interval.ms"
    MAX_POLL_RECORDS_CONFIG = "max.poll.records"
    METADATA_MAX_AGE_CONFIG = "metadata.max.age.ms"
    METRIC_REPORTER_CLASSES_CONFIG = "metric.reporters"
    METRICS_NUM_SAMPLES_CONFIG = "metrics.num.samples"
    METRICS_RECORDING_LEVEL_CONFIG = "metrics.recording.level"
    METRICS_SAMPLE_WINDOW_MS_CONFIG = "metrics.sample.window.ms"
    PARTITION_ASSIGNMENT_STRATEGY_CONFIG = "partition.assignment.strategy"
    RECEIVE_BUFFER_CONFIG = "receive.buffer.bytes"
    RECONNECT_BACKOFF_MAX_MS_CONFIG = "reconnect.backoff.max.ms"
    RECONNECT_BACKOFF_MS_CONFIG = "reconnect.backoff.ms"
    REQUEST_TIMEOUT_MS_CONFIG = "request.timeout.ms"
    RETRY_BACKOFF_MS_CONFIG = "retry.backoff.ms"
    SEND_BUFFER_CONFIG = "send.buffer.bytes"
    SESSION_TIMEOUT_MS_CONFIG = "session.timeout.ms"
    VALUE_DESERIALIZER_CLASS_CONFIG = "value.deserializer"
​
​
class ProducerConfig:
    """
    Configuration for the Kafka Producer.
    """
    ACKS_CONFIG = "acks"
    BATCH_SIZE_CONFIG = "batch.size"
    BOOTSTRAP_SERVERS_CONFIG = "bootstrap.servers"
    BUFFER_MEMORY_CONFIG = "buffer.memory"
    CLIENT_ID_CONFIG = "client.id"
    COMPRESSION_TYPE_CONFIG = "compression.type"
    CONNECTIONS_MAX_IDLE_MS_CONFIG = "connections.max.idle.ms"
    ENABLE_IDEMPOTENCE_CONFIG = "enable.idempotence"
    INTERCEPTOR_CLASSES_CONFIG = "interceptor.classes"
    KEY_SERIALIZER_CLASS_CONFIG = "key.serializer"
    LINGER_MS_CONFIG = "linger.ms"
    MAX_BLOCK_MS_CONFIG = "max.block.ms"
    MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION = "max.in.flight.requests.per.connection"
    MAX_REQUEST_SIZE_CONFIG = "max.request.size"
    METADATA_MAX_AGE_CONFIG = "metadata.max.age.ms"
    METRIC_REPORTER_CLASSES_CONFIG = "metric.reporters"
    METRICS_NUM_SAMPLES_CONFIG = "metrics.num.samples"
    METRICS_RECORDING_LEVEL_CONFIG = "metrics.recording.level"
    METRICS_SAMPLE_WINDOW_MS_CONFIG = "metrics.sample.window.ms"
    PARTITIONER_CLASS_CONFIG = "partitioner.class"
    RECEIVE_BUFFER_CONFIG = "receive.buffer.bytes"
    RECONNECT_BACKOFF_MAX_MS_CONFIG = "reconnect.backoff.max.ms"
    RECONNECT_BACKOFF_MS_CONFIG = "reconnect.backoff.ms"
    REQUEST_TIMEOUT_MS_CONFIG = "request.timeout.ms"
    RETRIES_CONFIG = "retries"
    RETRY_BACKOFF_MS_CONFIG = "retry.backoff.ms"
    SEND_BUFFER_CONFIG = "send.buffer.bytes"
    TRANSACTION_TIMEOUT_CONFIG = "transaction.timeout.ms"
    TRANSACTIONAL_ID_CONFIG = "transactional.id"
    VALUE_SERIALIZER_CLASS_CONFIG = "value.serializer"
