# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: c8_inline.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'c8_inline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import confluent_kafka.schema_registry.confluent.meta_pb2 as confluent_dot_meta__pb2
import confluent_kafka.schema_registry.confluent.types.decimal_pb2 as confluent_dot_types_dot_decimal__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x38_inline.proto\x12\x05tests\x1a\x14\x63onfluent/meta.proto\x1a\x1d\x63onfluent/types/decimal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x02\n\x08\x43\x38Inline\x12[\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x17.confluent.type.DecimalB2\x82\x44/\"-\n\x06\x66ldDec\x1a#decimals.gt(this, decimal(\'10.00\'))\x12^\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB6\x82\x44\x33\"1\n\x05\x66ldTs\x1a(this > timestamp(\'2000-01-01T00:00:00Z\')\x12\r\n\x05label\x18\x03 \x01(\t:o\x82\x44l\"4\n\x06msgDec\x1a*decimals.gt(this.amount, decimal(\'10.00\'))\"4\n\x05msgTs\x1a+this.ts > timestamp(\'2000-01-01T00:00:00Z\')\"\xb5\x03\n\x0c\x43\x39\x43ontainers\x12g\n\x07\x61mounts\x18\x01 \x03(\x0b\x32\x17.confluent.type.DecimalB=\x82\x44:\x1a\x07\x41MOUNTS\"/\n\x06\x66ldArr\x1a%decimals.gt(this[0], decimal(\'1.00\'))\x12\x46\n\namount_map\x18\x02 \x03(\x0b\x32\".tests.C9Containers.AmountMapEntryB\x0e\x82\x44\x0b\x1a\tAMOUNTMAP\x12\x1e\n\x06nested\x18\x03 \x01(\x0b\x32\x0e.tests.C9Inner\x12\r\n\x05label\x18\x04 \x01(\t\x1aI\n\x0e\x41mountMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.confluent.type.Decimal:\x02\x38\x01:z\x82\x44w\"7\n\x06msgArr\x1a-decimals.gt(this.amounts[0], decimal(\'1.00\'))\"<\n\tmsgNested\x1a/decimals.gt(this.nested.inner, decimal(\'1.00\'))\"m\n\x07\x43\x39Inner\x12\x62\n\x05inner\x18\x01 \x01(\x0b\x32\x17.confluent.type.DecimalB:\x82\x44\x37\x1a\x05INNER\".\n\x08\x66ldInner\x1a\"decimals.gt(this, decimal(\'1.00\'))b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c8_inline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_C8INLINE'].fields_by_name['amount']._loaded_options = None
  _globals['_C8INLINE'].fields_by_name['amount']._serialized_options = b'\202D/\"-\n\006fldDec\032#decimals.gt(this, decimal(\'10.00\'))'
  _globals['_C8INLINE'].fields_by_name['ts']._loaded_options = None
  _globals['_C8INLINE'].fields_by_name['ts']._serialized_options = b'\202D3\"1\n\005fldTs\032(this > timestamp(\'2000-01-01T00:00:00Z\')'
  _globals['_C8INLINE']._loaded_options = None
  _globals['_C8INLINE']._serialized_options = b'\202Dl\"4\n\006msgDec\032*decimals.gt(this.amount, decimal(\'10.00\'))\"4\n\005msgTs\032+this.ts > timestamp(\'2000-01-01T00:00:00Z\')'
  _globals['_C9CONTAINERS_AMOUNTMAPENTRY']._loaded_options = None
  _globals['_C9CONTAINERS_AMOUNTMAPENTRY']._serialized_options = b'8\001'
  _globals['_C9CONTAINERS'].fields_by_name['amounts']._loaded_options = None
  _globals['_C9CONTAINERS'].fields_by_name['amounts']._serialized_options = b'\202D:\032\007AMOUNTS\"/\n\006fldArr\032%decimals.gt(this[0], decimal(\'1.00\'))'
  _globals['_C9CONTAINERS'].fields_by_name['amount_map']._loaded_options = None
  _globals['_C9CONTAINERS'].fields_by_name['amount_map']._serialized_options = b'\202D\013\032\tAMOUNTMAP'
  _globals['_C9CONTAINERS']._loaded_options = None
  _globals['_C9CONTAINERS']._serialized_options = b'\202Dw\"7\n\006msgArr\032-decimals.gt(this.amounts[0], decimal(\'1.00\'))\"<\n\tmsgNested\032/decimals.gt(this.nested.inner, decimal(\'1.00\'))'
  _globals['_C9INNER'].fields_by_name['inner']._loaded_options = None
  _globals['_C9INNER'].fields_by_name['inner']._serialized_options = b'\202D7\032\005INNER\".\n\010fldInner\032\"decimals.gt(this, decimal(\'1.00\'))'
  _globals['_C8INLINE']._serialized_start=113
  _globals['_C8INLINE']._serialized_end=440
  _globals['_C9CONTAINERS']._serialized_start=443
  _globals['_C9CONTAINERS']._serialized_end=880
  _globals['_C9CONTAINERS_AMOUNTMAPENTRY']._serialized_start=683
  _globals['_C9CONTAINERS_AMOUNTMAPENTRY']._serialized_end=756
  _globals['_C9INNER']._serialized_start=882
  _globals['_C9INNER']._serialized_end=991
# @@protoc_insertion_point(module_scope)
