# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_widget.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10map_widget.proto\x12\x04test\"\x83\x01\n\tMapWidget\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x06labels\x18\x02 \x03(\x0b\x32\x1b.test.MapWidget.LabelsEntry\x12\x0c\n\x04tags\x18\x03 \x03(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\tZ\x07../testb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_widget_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\007../test'
    _globals['_MAPWIDGET_LABELSENTRY']._loaded_options = None
    _globals['_MAPWIDGET_LABELSENTRY']._serialized_options = b'8\001'
    _globals['_MAPWIDGET']._serialized_start = 27
    _globals['_MAPWIDGET']._serialized_end = 158
    _globals['_MAPWIDGET_LABELSENTRY']._serialized_start = 113
    _globals['_MAPWIDGET_LABELSENTRY']._serialized_end = 158
# @@protoc_insertion_point(module_scope)
