# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validation_widget.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

import confluent_kafka.schema_registry.confluent.meta_pb2 as confluent_dot_meta__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17validation_widget.proto\x12\x04test\x1a\x14\x63onfluent/meta.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n\x10ValidationPerson\x12\x44\n\x03\x61ge\x18\x01 \x01(\x05\x42\x37\x82\x44\x34\"2\n\x0b\x61gePositive\x12\x18\x61ge must not be negative\x1a\tthis >= 0\x12\x31\n\x04name\x18\x02 \x01(\tB#\x82\x44 \"\x1e\n\x0cnameNotEmpty\x1a\x0esize(this) > 0:$\x82\x44!\"\x1f\n\x0c\x61geNotInsane\x1a\x0fthis.age <= 150\"0\n\x0fValidationInner\x12\x1d\n\x01x\x18\x01 \x01(\x05\x42\x12\x82\x44\x0f\"\r\n\x01r\x1a\x08this > 0\"8\n\x0eValidationItem\x12\t\n\x01v\x18\x01 \x01(\x05:\x1b\x82\x44\x18\"\x16\n\x08itemRule\x1a\nthis.v > 0\"\xcb\x02\n\x0fValidationOuter\x12$\n\x05inner\x18\x01 \x01(\x0b\x32\x15.test.ValidationInner\x12#\n\x05items\x18\x02 \x03(\x0b\x32\x14.test.ValidationItem\x12\x38\n\x05maybe\x18\x03 \x01(\tB$\x82\x44!\"\x1f\n\rmaybeNotEmpty\x1a\x0esize(this) > 0H\x00\x88\x01\x01\x12\x31\n\x06labels\x18\x04 \x03(\x0b\x32!.test.ValidationOuter.LabelsEntry\x12\x31\n\x04tags\x18\x05 \x03(\tB#\x82\x44 \"\x1e\n\x0ctagsNotEmpty\x1a\x0esize(this) > 0\x1a\x43\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.test.ValidationItem:\x02\x38\x01\x42\x08\n\x06_maybe\"`\n\x0fValidationEvent\x12M\n\ncreated_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x1d\x82\x44\x1a\"\x18\n\tnotFuture\x1a\x0bthis <= now\"t\n\x18ValidationDynamicMessage\x12X\n\x03\x61ge\x18\x01 \x01(\x05\x42K\x82\x44H\"F\n\x06\x61geMsg\x1a<this >= 0 ? \'\' : \'age must be positive, got \' + string(this)B\tZ\x07../testb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'validation_widget_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\007../test'
    _globals['_VALIDATIONPERSON'].fields_by_name['age']._loaded_options = None
    _globals['_VALIDATIONPERSON'].fields_by_name[
        'age'
    ]._serialized_options = b'\202D4\"2\n\013agePositive\022\030age must not be negative\032\tthis >= 0'
    _globals['_VALIDATIONPERSON'].fields_by_name['name']._loaded_options = None
    _globals['_VALIDATIONPERSON'].fields_by_name[
        'name'
    ]._serialized_options = b'\202D \"\036\n\014nameNotEmpty\032\016size(this) > 0'
    _globals['_VALIDATIONPERSON']._loaded_options = None
    _globals['_VALIDATIONPERSON']._serialized_options = b'\202D!\"\037\n\014ageNotInsane\032\017this.age <= 150'
    _globals['_VALIDATIONINNER'].fields_by_name['x']._loaded_options = None
    _globals['_VALIDATIONINNER'].fields_by_name['x']._serialized_options = b'\202D\017\"\r\n\001r\032\010this > 0'
    _globals['_VALIDATIONITEM']._loaded_options = None
    _globals['_VALIDATIONITEM']._serialized_options = b'\202D\030\"\026\n\010itemRule\032\nthis.v > 0'
    _globals['_VALIDATIONOUTER_LABELSENTRY']._loaded_options = None
    _globals['_VALIDATIONOUTER_LABELSENTRY']._serialized_options = b'8\001'
    _globals['_VALIDATIONOUTER'].fields_by_name['maybe']._loaded_options = None
    _globals['_VALIDATIONOUTER'].fields_by_name[
        'maybe'
    ]._serialized_options = b'\202D!\"\037\n\rmaybeNotEmpty\032\016size(this) > 0'
    _globals['_VALIDATIONOUTER'].fields_by_name['tags']._loaded_options = None
    _globals['_VALIDATIONOUTER'].fields_by_name[
        'tags'
    ]._serialized_options = b'\202D \"\036\n\014tagsNotEmpty\032\016size(this) > 0'
    _globals['_VALIDATIONEVENT'].fields_by_name['created_at']._loaded_options = None
    _globals['_VALIDATIONEVENT'].fields_by_name[
        'created_at'
    ]._serialized_options = b'\202D\032\"\030\n\tnotFuture\032\013this <= now'
    _globals['_VALIDATIONDYNAMICMESSAGE'].fields_by_name['age']._loaded_options = None
    _globals['_VALIDATIONDYNAMICMESSAGE'].fields_by_name[
        'age'
    ]._serialized_options = (
        b'\202DH\"F\n\006ageMsg\032<this >= 0 ? \'\' : \'age must be positive, got \' + string(this)'
    )
    _globals['_VALIDATIONPERSON']._serialized_start = 89
    _globals['_VALIDATIONPERSON']._serialized_end = 266
    _globals['_VALIDATIONINNER']._serialized_start = 268
    _globals['_VALIDATIONINNER']._serialized_end = 316
    _globals['_VALIDATIONITEM']._serialized_start = 318
    _globals['_VALIDATIONITEM']._serialized_end = 374
    _globals['_VALIDATIONOUTER']._serialized_start = 377
    _globals['_VALIDATIONOUTER']._serialized_end = 708
    _globals['_VALIDATIONOUTER_LABELSENTRY']._serialized_start = 631
    _globals['_VALIDATIONOUTER_LABELSENTRY']._serialized_end = 698
    _globals['_VALIDATIONEVENT']._serialized_start = 710
    _globals['_VALIDATIONEVENT']._serialized_end = 806
    _globals['_VALIDATIONDYNAMICMESSAGE']._serialized_start = 808
    _globals['_VALIDATIONDYNAMICMESSAGE']._serialized_end = 924
# @@protoc_insertion_point(module_scope)
