# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: value_types.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'value_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import confluent_kafka.schema_registry.confluent.meta_pb2 as confluent_dot_meta__pb2
import confluent_kafka.schema_registry.confluent.types.decimal_pb2 as confluent_dot_types_dot_decimal__pb2
import confluent_kafka.schema_registry.confluent.types.variant_pb2 as confluent_dot_types_dot_variant__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11value_types.proto\x12\x05tests\x1a\x14\x63onfluent/meta.proto\x1a\x1d\x63onfluent/types/decimal.proto\x1a\x1d\x63onfluent/types/variant.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n\nValueTypes\x12\x34\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x17.confluent.type.DecimalB\x0b\x82\x44\x08\x1a\x06\x41MOUNT\x12/\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x07\x82\x44\x04\x1a\x02TS\x12\x30\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.confluent.type.VariantB\t\x82\x44\x06\x1a\x04\x44\x41TA\x12\x19\n\x05label\x18\x04 \x01(\tB\n\x82\x44\x07\x1a\x05LABEL\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'value_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUETYPES'].fields_by_name['amount']._loaded_options = None
  _globals['_VALUETYPES'].fields_by_name['amount']._serialized_options = b'\202D\010\032\006AMOUNT'
  _globals['_VALUETYPES'].fields_by_name['ts']._loaded_options = None
  _globals['_VALUETYPES'].fields_by_name['ts']._serialized_options = b'\202D\004\032\002TS'
  _globals['_VALUETYPES'].fields_by_name['data']._loaded_options = None
  _globals['_VALUETYPES'].fields_by_name['data']._serialized_options = b'\202D\006\032\004DATA'
  _globals['_VALUETYPES'].fields_by_name['label']._loaded_options = None
  _globals['_VALUETYPES'].fields_by_name['label']._serialized_options = b'\202D\007\032\005LABEL'
  _globals['_VALUETYPES']._serialized_start=146
  _globals['_VALUETYPES']._serialized_end=353
# @@protoc_insertion_point(module_scope)
