# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: value_type_rules.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

import confluent_kafka.schema_registry.confluent.meta_pb2 as confluent_dot_meta__pb2
import confluent_kafka.schema_registry.confluent.types.decimal_pb2 as confluent_dot_types_dot_decimal__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16value_type_rules.proto\x12\x05tests\x1a\x14\x63onfluent/meta.proto\x1a\x1d\x63onfluent/types/decimal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n\x10InlineValueTypes\x12[\n\x06\x61mount\x18\x01 \x01(\x0b\x32\x17.confluent.type.DecimalB2\x82\x44/\"-\n\x06\x66ldDec\x1a#decimals.gt(this, decimal(\'10.00\'))\x12^\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB6\x82\x44\x33\"1\n\x05\x66ldTs\x1a(this > timestamp(\'2000-01-01T00:00:00Z\')\x12\r\n\x05label\x18\x03 \x01(\t:o\x82\x44l\"4\n\x06msgDec\x1a*decimals.gt(this.amount, decimal(\'10.00\'))\"4\n\x05msgTs\x1a+this.ts > timestamp(\'2000-01-01T00:00:00Z\')\"\xf2\x03\n\x13ValueTypeContainers\x12g\n\x07\x61mounts\x18\x01 \x03(\x0b\x32\x17.confluent.type.DecimalB=\x82\x44:\x1a\x07\x41MOUNTS\"/\n\x06\x66ldArr\x1a%decimals.gt(this[0], decimal(\'1.00\'))\x12M\n\namount_map\x18\x02 \x03(\x0b\x32).tests.ValueTypeContainers.AmountMapEntryB\x0e\x82\x44\x0b\x1a\tAMOUNTMAP\x12&\n\x06nested\x18\x03 \x01(\x0b\x32\x16.tests.ValueTypeNested\x12\x19\n\x05label\x18\x04 \x01(\tB\n\x82\x44\x07\x1a\x05LABEL\x12\x19\n\x05\x63odes\x18\x05 \x03(\tB\n\x82\x44\x07\x1a\x05\x43ODES\x1aI\n\x0e\x41mountMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.confluent.type.Decimal:\x02\x38\x01:z\x82\x44w\"7\n\x06msgArr\x1a-decimals.gt(this.amounts[0], decimal(\'1.00\'))\"<\n\tmsgNested\x1a/decimals.gt(this.nested.inner, decimal(\'1.00\'))\"u\n\x0fValueTypeNested\x12\x62\n\x05inner\x18\x01 \x01(\x0b\x32\x17.confluent.type.DecimalB:\x82\x44\x37\x1a\x05INNER\".\n\x08\x66ldInner\x1a\"decimals.gt(this, decimal(\'1.00\'))b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'value_type_rules_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_INLINEVALUETYPES'].fields_by_name['amount']._loaded_options = None
    _globals['_INLINEVALUETYPES'].fields_by_name[
        'amount'
    ]._serialized_options = b'\202D/\"-\n\006fldDec\032#decimals.gt(this, decimal(\'10.00\'))'
    _globals['_INLINEVALUETYPES'].fields_by_name['ts']._loaded_options = None
    _globals['_INLINEVALUETYPES'].fields_by_name[
        'ts'
    ]._serialized_options = b'\202D3\"1\n\005fldTs\032(this > timestamp(\'2000-01-01T00:00:00Z\')'
    _globals['_INLINEVALUETYPES']._loaded_options = None
    _globals['_INLINEVALUETYPES']._serialized_options = (
        b'\202Dl\"4\n\006msgDec\032*decimals.gt(this.amount, decimal(\'10.00\'))\"4\n\005msgTs\032+this.ts > timestamp(\'2000-01-01T00:00:00Z\')'
    )
    _globals['_VALUETYPECONTAINERS_AMOUNTMAPENTRY']._loaded_options = None
    _globals['_VALUETYPECONTAINERS_AMOUNTMAPENTRY']._serialized_options = b'8\001'
    _globals['_VALUETYPECONTAINERS'].fields_by_name['amounts']._loaded_options = None
    _globals['_VALUETYPECONTAINERS'].fields_by_name[
        'amounts'
    ]._serialized_options = b'\202D:\032\007AMOUNTS\"/\n\006fldArr\032%decimals.gt(this[0], decimal(\'1.00\'))'
    _globals['_VALUETYPECONTAINERS'].fields_by_name['amount_map']._loaded_options = None
    _globals['_VALUETYPECONTAINERS'].fields_by_name['amount_map']._serialized_options = b'\202D\013\032\tAMOUNTMAP'
    _globals['_VALUETYPECONTAINERS'].fields_by_name['label']._loaded_options = None
    _globals['_VALUETYPECONTAINERS'].fields_by_name['label']._serialized_options = b'\202D\007\032\005LABEL'
    _globals['_VALUETYPECONTAINERS'].fields_by_name['codes']._loaded_options = None
    _globals['_VALUETYPECONTAINERS'].fields_by_name['codes']._serialized_options = b'\202D\007\032\005CODES'
    _globals['_VALUETYPECONTAINERS']._loaded_options = None
    _globals['_VALUETYPECONTAINERS']._serialized_options = (
        b'\202Dw\"7\n\006msgArr\032-decimals.gt(this.amounts[0], decimal(\'1.00\'))\"<\n\tmsgNested\032/decimals.gt(this.nested.inner, decimal(\'1.00\'))'
    )
    _globals['_VALUETYPENESTED'].fields_by_name['inner']._loaded_options = None
    _globals['_VALUETYPENESTED'].fields_by_name[
        'inner'
    ]._serialized_options = b'\202D7\032\005INNER\".\n\010fldInner\032\"decimals.gt(this, decimal(\'1.00\'))'
    _globals['_INLINEVALUETYPES']._serialized_start = 120
    _globals['_INLINEVALUETYPES']._serialized_end = 455
    _globals['_VALUETYPECONTAINERS']._serialized_start = 458
    _globals['_VALUETYPECONTAINERS']._serialized_end = 956
    _globals['_VALUETYPECONTAINERS_AMOUNTMAPENTRY']._serialized_start = 759
    _globals['_VALUETYPECONTAINERS_AMOUNTMAPENTRY']._serialized_end = 832
    _globals['_VALUETYPENESTED']._serialized_start = 958
    _globals['_VALUETYPENESTED']._serialized_end = 1075
# @@protoc_insertion_point(module_scope)
